name: PHP Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Download and unzip the CLDR core.zip
    - name: Download CLDR core.zip
      if: github.ref == 'refs/heads/main'
      run: |
        wget http://www.unicode.org/Public/cldr/latest/core.zip
        unzip core.zip
        mv common/main/ ./
        rm -rf data/

    # Step 3: Run the language-codes.sh script
    - name: Run language-codes.sh
      run: ./language-codes.sh

    # Step 4: Run the PHP script
    - name: Run PHP Script
      run: php ietf-lanGen.php

    # Step 5: Install npm packages and push data using data-cli
    - name: Install data-cli and push data
      run: |
        npm install data-cli --global
        data push
